### ISSUE TITLE
why is struglog dev optional dependency included in the setup.py?

### ISSUE THREAD

**Issue by amolinaalvarez** [closeio/socketshark#160]
Hi, I would like to clarify why is `structlog` `dev` optional dependency included in the `setup.py` file as a part of `install_requires`?

```
install_requires = [
    'aiohttp',
    'aioredis',
    'click',
    'structlog[dev]',  <---
    'websockets',
]
```

Thank you in advanced.

**Comment by AlecRosenbaum** [comment]
Good question, it seems like it's been that way since it was introduced in 2017. It was probably an oversight or was related to how structlog existed at the time.

Seems like something we should remove.

Would you like to open a PR for it?

**Comment by amolinaalvarez** [comment]
@AlecRosenbaum https://github.com/closeio/socketshark/pull/165

Thank you.
